# Change these first
owner: UEM-Group-Websites # Your GitHub organization or username, where this repository lives
repo: uptime-checker # The name of this repository

sites:
  - name: UEM Main Website
    url: https://uem.edu.in/site-health-page/
  - name: IEM Main Website
    url: https://iem.edu.in/site-health-page/
    header:
      User-Agent: "github.com/uptime/uptime-monitor"
  - name: UEM Jaipur Website
    url: https://uem.edu.in/uem-jaipur/site-health-page/
  - name: UEM Kolkata Website
    url: https://uem.edu.in/uem-kolkata/site-health-page/
  - name: UEM Staging Main Website
    url: https://staging.uem.edu.in/site-health-page/
  - name: UEM Staging Jaipur Website
    url: https://staging.uem.edu.in/uem-jaipur/site-health-page/
  - name: UEM Staging Kolkata Website
    url: https://staging.uem.edu.in/uem-kolkata/site-health-page/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.uem.edu.in
  # baseUrl: /your-repo-name
  logoUrl: https://uem.edu.in/app/themes/iem-group-new-wp-theme/resources/images/UEM-Logo.avif
  name: IEM/UEM
  introTitle: "IEM/UEM Group Uptime Status"
  introMessage: The IEM UEM group is an acclaimed educational group amongst the industry-centred academic training organisations of today. IEM has set sublime standards in addressing the technical and managerial resource shortage in the new era of dynamic globalisation.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/UEM-Group-Websites/uptime-checker
  metaTags:
    - name: robots
      content: noindex, nofollow

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
